name: '✨ Feature Request'
description: Suggest an idea or feature enhancement for Overtone
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an enhancement for Overtone!
  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: Is your feature request related to a problem or limitation? Please describe.
      placeholder: 'I often find that...'
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: 'Add support for...'
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
  - type: checkboxes
    id: contribute
    attributes:
      label: Willingness to Contribute
      options:
        - label: I would be willing to submit a PR for this feature
